package imguploader

import (
	"context"
	"fmt"
	"os"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/feature/s3/manager"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"
	"github.com/grafana/grafana/pkg/infra/log"
	"github.com/grafana/grafana/pkg/util"
)

type S3Uploader struct {
	endpoint        string
	region          string
	bucket          string
	path            string
	acl             types.ObjectCannedACL
	secretKey       string
	accessKey       string
	pathStyleAccess bool
	log             log.Logger
}

func NewS3Uploader(endpoint, region, bucket, path string, acl types.ObjectCannedACL, accessKey, secretKey string, pathStyleAccess bool) *S3Uploader {
	return &S3Uploader{
		endpoint:        endpoint,
		region:          region,
		bucket:          bucket,
		path:            path,
		acl:             acl,
		accessKey:       accessKey,
		secretKey:       secretKey,
		pathStyleAccess: pathStyleAccess,
		log:             log.New("s3uploader"),
	}
}

func (u *S3Uploader) Upload(ctx context.Context, imageDiskPath string) (string, error) {
	configOpts := []func(*config.LoadOptions) error{
		config.WithRegion(u.region),
	}
	if u.accessKey != "" && u.secretKey != "" {
		configOpts = append(configOpts,
			config.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(u.accessKey, u.secretKey, "")),
		)
	}

	cfg, err := config.LoadDefaultConfig(ctx, configOpts...)
	if err != nil {
		return "", fmt.Errorf("loading AWS config: %w", err)
	}

	client := s3.NewFromConfig(cfg, func(o *s3.Options) {
		if u.endpoint != "" {
			o.BaseEndpoint = aws.String(u.endpoint)
		}
		o.UsePathStyle = u.pathStyleAccess
	})

	rand, err := util.GetRandomString(20)
	if err != nil {
		return "", err
	}
	key := u.path + rand + pngExt
	u.log.Debug("Uploading image to s3.", "bucket", u.bucket, "path", key)

	// We can ignore the gosec G304 warning on this one because `imageDiskPath` comes
	// from alert notifiers and is only used to upload images generated by alerting.
	// nolint:gosec
	file, err := os.Open(imageDiskPath)
	if err != nil {
		return "", err
	}
	defer func() {
		if err := file.Close(); err != nil {
			u.log.Warn("Failed to close file", "path", imageDiskPath, "err", err)
		}
	}()

	result, err := manager.NewUploader(client).Upload(ctx, &s3.PutObjectInput{
		Bucket:      aws.String(u.bucket),
		Key:         aws.String(key),
		ACL:         u.acl,
		Body:        file,
		ContentType: aws.String("image/png"),
	})
	if err != nil {
		return "", fmt.Errorf("uploading to S3: %w", err)
	}
	return result.Location, nil
}
